#pragma once

#include <expected>
#include <optional>
#include <string>
#include <string_view>
#include <vector>

namespace ad::core {

using CityId = int;
using CountryIndex = int;

struct Country {
  CountryIndex index{};
  std::string key;        // ISO 3166-1 alpha-2, lower case: "fr"
  std::string name;       // "France"
  std::string shortName;  // "France"
  std::string iso3;       // "FRA"
  std::string continent;
  long long population{};
  long long gdp{};        // current USD
  int gdpYear{};          // 0 when the Natural Earth fallback was used
  std::string color;      // "#rrggbb" banner colour
  CityId capital{};
  std::string sovereign;
  std::vector<CityId> cities;  // ascending id
};

struct City {
  CityId id{};
  std::string key;        // "fr-paris"
  std::string name;
  CountryIndex country{};
  double lon{}, lat{};
  double x{}, y{};        // map units (docs/DATA_PIPELINE.md §3)
  long long population{};
  int tier{};
  bool capital{};
  std::vector<CityId> neighbours;  // ascending id, symmetric
};

struct Link {
  CityId a{}, b{};        // a < b
  bool sea{};
  bool wrap{};            // crosses the antimeridian
  int km{};
};

struct Projection {
  double width{}, height{};
  double latMin{}, latMax{};
};

/// The immutable world: countries, cities and links as generated by
/// scripts/gen_world_data.py. Loaded once, shared by every campaign.
class World {
public:
  /// Parse and validate world.json; the error names the offending record.
  [[nodiscard]] static std::expected<World, std::string> fromJson(std::string_view text);

  [[nodiscard]] const std::vector<Country>& countries() const noexcept { return countries_; }
  [[nodiscard]] const std::vector<City>& cities() const noexcept { return cities_; }
  [[nodiscard]] const std::vector<Link>& links() const noexcept { return links_; }
  [[nodiscard]] const Projection& projection() const noexcept { return projection_; }
  [[nodiscard]] const std::string& hash() const noexcept { return hash_; }

  [[nodiscard]] const Country& country(CountryIndex i) const noexcept { return countries_[static_cast<std::size_t>(i)]; }
  [[nodiscard]] const City& city(CityId id) const noexcept { return cities_[static_cast<std::size_t>(id)]; }
  [[nodiscard]] std::optional<CountryIndex> countryByKey(std::string_view key) const noexcept;
  [[nodiscard]] std::optional<CityId> cityByKey(std::string_view key) const noexcept;
  [[nodiscard]] bool linked(CityId a, CityId b) const noexcept;
  [[nodiscard]] const std::vector<CityId>& neighbours(CityId id) const noexcept { return city(id).neighbours; }

private:
  std::vector<Country> countries_;
  std::vector<City> cities_;
  std::vector<Link> links_;
  Projection projection_;
  std::string hash_;
};

} // namespace ad::core
